services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-lynq_db}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    volumes:
      - redisdata_prod:/data
    restart: always

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-lynq_db}?sslmode=disable
      - REDIS_URL=redis:6379
    depends_on:
      - postgres
      - redis
    restart: always

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    deploy:
      replicas: 2
    env_file:
      - .env
    environment:
      - DB_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-lynq_db}?sslmode=disable
      - REDIS_URL=redis:6379
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  pgdata_prod:
  redisdata_prod:
